[project]
name = "code-template"
version = "0.1.0"
description = "Personal code template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
